version: 0.1


phases:
  build:
    commands:
      - wget https://s3.amazonaws.com/project2-ers-dependencies/ojdbc7.jar
      - mvn install:install-file -Dfile="ojdbc7.jar" -DgroupId="com.oracle" -DartifactId="ojdbc7" -Dversion="12.1.0" -Dpackaging="jar"
      - mvn clean package
artifacts:
  files: 
    - target/ERS.war
